export interface VerbItem {
  infinitive: string;
  pastSimple: string;
  pastParticiple: string;
  spanish: string;
  type: 'irregular' | 'regular';
  category?: 'frequent' | 'essential';
  example: string;
}

export const TOEIC_VERBS: VerbItem[] = [
  // Irregular Verbs (Top Frequency in TOEIC)
  { infinitive: 'arise', pastSimple: 'arose', pastParticiple: 'arisen', spanish: 'surgir / presentarse', type: 'irregular', example: 'Unexpected complications arose during the quarterly audit.' },
  { infinitive: 'be (am/is/are)', pastSimple: 'was/were', pastParticiple: 'been', spanish: 'ser / estar', type: 'irregular', example: 'The regional director has been in Tokyo since Monday.' },
  { infinitive: 'bear', pastSimple: 'bore', pastParticiple: 'borne', spanish: 'soportar / asumir', type: 'irregular', example: 'The company will bear all transportation expenses.' },
  { infinitive: 'become', pastSimple: 'became', pastParticiple: 'become', spanish: 'llegar a ser / convertirse', type: 'irregular', example: 'Online sales became our primary revenue stream last year.' },
  { infinitive: 'begin', pastSimple: 'began', pastParticiple: 'begun', spanish: 'comenzar / empezar', type: 'irregular', example: 'The orientation session began promptly at nine o’clock.' },
  { infinitive: 'break', pastSimple: 'broke', pastParticiple: 'broken', spanish: 'romper / quebrar', type: 'irregular', example: 'The copy machine broke down right before the deadline.' },
  { infinitive: 'bring', pastSimple: 'brought', pastParticiple: 'brought', spanish: 'traer / aportar', type: 'irregular', example: 'She brought extensive marketing experience to our team.' },
  { infinitive: 'build', pastSimple: 'built', pastParticiple: 'built', spanish: 'construir / edificar', type: 'irregular', example: 'The firm built a modern research facility near the harbor.' },
  { infinitive: 'buy', pastSimple: 'bought', pastParticiple: 'bought', spanish: 'comprar / adquirir', type: 'irregular', example: 'They bought upgraded licenses for all remote employees.' },
  { infinitive: 'catch', pastSimple: 'caught', pastParticiple: 'caught', spanish: 'atrapar / tomar (transporte)', type: 'irregular', example: 'He caught the express shuttle to Terminal 3.' },
  { infinitive: 'choose', pastSimple: 'chose', pastParticiple: 'chosen', spanish: 'elegir / seleccionar', type: 'irregular', example: 'The committee has chosen the most cost-effective vendor.' },
  { infinitive: 'come', pastSimple: 'came', pastParticiple: 'come', spanish: 'venir / llegar', type: 'irregular', example: 'Inspectors came to inspect the assembly plant yesterday.' },
  { infinitive: 'cost', pastSimple: 'cost', pastParticiple: 'cost', spanish: 'costar / implicar gasto', type: 'irregular', example: 'Renovating the headquarters cost more than anticipated.' },
  { infinitive: 'cut', pastSimple: 'cut', pastParticiple: 'cut', spanish: 'cortar / reducir', type: 'irregular', example: 'Management cut operational overhead by twelve percent.' },
  { infinitive: 'deal', pastSimple: 'dealt', pastParticiple: 'dealt', spanish: 'tratar / negociar', type: 'irregular', example: 'Our customer support team dealt with the complaint swiftly.' },
  { infinitive: 'do', pastSimple: 'did', pastParticiple: 'done', spanish: 'hacer / realizar', type: 'irregular', example: 'The external agency did a comprehensive market survey.' },
  { infinitive: 'draw', pastSimple: 'drew', pastParticiple: 'drawn', spanish: 'dibujar / atraer', type: 'irregular', example: 'The keynote speaker drew a crowd of hundreds of delegates.' },
  { infinitive: 'drive', pastSimple: 'drove', pastParticiple: 'driven', spanish: 'conducir / impulsar', type: 'irregular', example: 'Technological innovation drove sales growth this quarter.' },
  { infinitive: 'fall', pastSimple: 'fell', pastParticiple: 'fallen', spanish: 'caer / descender', type: 'irregular', example: 'Share prices fell slightly after the announcement.' },
  { infinitive: 'feel', pastSimple: 'felt', pastParticiple: 'felt', spanish: 'sentir / opinar', type: 'irregular', example: 'Employees felt that the new policy was fair and flexible.' },
  { infinitive: 'find', pastSimple: 'found', pastParticiple: 'found', spanish: 'encontrar / hallar', type: 'irregular', example: 'We found an alternative supplier with faster delivery.' },
  { infinitive: 'fly', pastSimple: 'flew', pastParticiple: 'flown', spanish: 'volar / viajar en avión', type: 'irregular', example: 'The executive flew to Singapore for contract negotiations.' },
  { infinitive: 'forget', pastSimple: 'forgot', pastParticiple: 'forgotten', spanish: 'olvidar', type: 'irregular', example: 'Do not forget to submit your travel receipts for reimbursement.' },
  { infinitive: 'get', pastSimple: 'got', pastParticiple: 'got / gotten', spanish: 'obtener / conseguir / llegar', type: 'irregular', example: 'She got approval for the project expansion.' },
  { infinitive: 'give', pastSimple: 'gave', pastParticiple: 'given', spanish: 'dar / otorgar', type: 'irregular', example: 'The supervisor gave clear guidelines for the assignment.' },
  { infinitive: 'go', pastSimple: 'went', pastParticiple: 'gone', spanish: 'ir / acudir', type: 'irregular', example: 'Several staff members went to the annual convention.' },
  { infinitive: 'grow', pastSimple: 'grew', pastParticiple: 'grown', spanish: 'crecer / aumentar', type: 'irregular', example: 'Our international client base grew rapidly last year.' },
  { infinitive: 'have', pastSimple: 'had', pastParticiple: 'had', spanish: 'tener / poseer', type: 'irregular', example: 'We had an informative conference call with the architects.' },
  { infinitive: 'hear', pastSimple: 'heard', pastParticiple: 'heard', spanish: 'oír / escuchar', type: 'irregular', example: 'We heard that the flight has been rescheduled.' },
  { infinitive: 'hold', pastSimple: 'held', pastParticiple: 'held', spanish: 'sostener / llevar a cabo (reunión)', type: 'irregular', example: 'The quarterly review will be held in Conference Room B.' },
  { infinitive: 'keep', pastSimple: 'kept', pastParticiple: 'kept', spanish: 'mantener / guardar', type: 'irregular', example: 'Please keep all confidential files in the secured folder.' },
  { infinitive: 'know', pastSimple: 'knew', pastParticiple: 'known', spanish: 'saber / conocer', type: 'irregular', example: 'The technician knew exactly how to fix the server issue.' },
  { infinitive: 'lead', pastSimple: 'led', pastParticiple: 'led', spanish: 'liderar / guiar / conducir a', type: 'irregular', example: 'Effective team coordination led to an on-time release.' },
  { infinitive: 'leave', pastSimple: 'left', pastParticiple: 'left', spanish: 'dejar / salir / marcharse', type: 'irregular', example: 'The express train left the platform five minutes ago.' },
  { infinitive: 'lose', pastSimple: 'lost', pastParticiple: 'lost', spanish: 'perder', type: 'irregular', example: 'The department lost crucial data due to a power outage.' },
  { infinitive: 'make', pastSimple: 'made', pastParticiple: 'made', spanish: 'hacer / fabricar', type: 'irregular', example: 'The committee made several constructive recommendations.' },
  { infinitive: 'meet', pastSimple: 'met', pastParticiple: 'met', spanish: 'conocer / reunirse / cumplir (requisito)', type: 'irregular', example: 'The proposal met all stringent safety specifications.' },
  { infinitive: 'pay', pastSimple: 'paid', pastParticiple: 'paid', spanish: 'pagar / abonar', type: 'irregular', example: 'Clients paid their invoices through our secure web portal.' },
  { infinitive: 'put', pastSimple: 'put', pastParticiple: 'put', spanish: 'poner / colocar', type: 'irregular', example: 'She put the updated agenda on the shared drive.' },
  { infinitive: 'read', pastSimple: 'read', pastParticiple: 'read', spanish: 'leer', type: 'irregular', example: 'The manager read the comprehensive summary before the meeting.' },
  { infinitive: 'rise', pastSimple: 'rose', pastParticiple: 'risen', spanish: 'subir / ascender (intransitivo)', type: 'irregular', example: 'Energy costs rose sharply during the winter quarter.' },
  { infinitive: 'run', pastSimple: 'ran', pastParticiple: 'run', spanish: 'correr / operar / dirigir', type: 'irregular', example: 'He ran the regional branch with great efficiency.' },
  { infinitive: 'say', pastSimple: 'said', pastParticiple: 'said', spanish: 'decir', type: 'irregular', example: 'The spokesperson said that deliveries would resume soon.' },
  { infinitive: 'see', pastSimple: 'saw', pastParticiple: 'seen', spanish: 'ver / comprobar', type: 'irregular', example: 'We saw significant improvement in overall customer ratings.' },
  { infinitive: 'seek', pastSimple: 'sought', pastParticiple: 'sought', spanish: 'buscar / solicitar', type: 'irregular', example: 'The company sought qualified candidates with bilingual skills.' },
  { infinitive: 'sell', pastSimple: 'sold', pastParticiple: 'sold', spanish: 'vender', type: 'irregular', example: 'The bookstore sold over five thousand copies in one week.' },
  { infinitive: 'send', pastSimple: 'sent', pastParticiple: 'sent', spanish: 'enviar / remitir', type: 'irregular', example: 'The human resources officer sent the offer letter by email.' },
  { infinitive: 'set', pastSimple: 'set', pastParticiple: 'set', spanish: 'establecer / fijar', type: 'irregular', example: 'The leadership set ambitious targets for sustainable packaging.' },
  { infinitive: 'show', pastSimple: 'showed', pastParticiple: 'shown', spanish: 'mostrar / exhibir', type: 'irregular', example: 'The graph clearly showed an upward trend in user retention.' },
  { infinitive: 'speak', pastSimple: 'spoke', pastParticiple: 'spoken', spanish: 'hablar / dirigirse', type: 'irregular', example: 'The CEO spoke about our transition to renewable energy.' },
  { infinitive: 'spend', pastSimple: 'spent', pastParticiple: 'spent', spanish: 'gastar / pasar tiempo', type: 'irregular', example: 'The team spent two weeks refining the mobile user interface.' },
  { infinitive: 'take', pastSimple: 'took', pastParticiple: 'taken', spanish: 'tomar / llevar', type: 'irregular', example: 'It took three working days to clear customs inspection.' },
  { infinitive: 'teach', pastSimple: 'taught', pastParticiple: 'taught', spanish: 'enseñar / capacitar', type: 'irregular', example: 'The instructor taught best practices in project management.' },
  { infinitive: 'tell', pastSimple: 'told', pastParticiple: 'told', spanish: 'decir / informar a alguien', type: 'irregular', example: 'She told the team that the launch date had been moved forward.' },
  { infinitive: 'think', pastSimple: 'thought', pastParticiple: 'thought', spanish: 'pensar / considerar', type: 'irregular', example: 'Most attendees thought the workshop was very informative.' },
  { infinitive: 'understand', pastSimple: 'understood', pastParticiple: 'understood', spanish: 'comprender / entender', type: 'irregular', example: 'Everyone understood the compliance protocols thoroughly.' },
  { infinitive: 'wear', pastSimple: 'wore', pastParticiple: 'worn', spanish: 'vestir / llevar puesto', type: 'irregular', example: 'All warehouse staff wore protective high-visibility vests.' },
  { infinitive: 'win', pastSimple: 'won', pastParticiple: 'won', spanish: 'ganar / obtener', type: 'irregular', example: 'Our creative agency won an international advertising prize.' },
  { infinitive: 'write', pastSimple: 'wrote', pastParticiple: 'written', spanish: 'escribir / redactar', type: 'irregular', example: 'The consultant wrote an in-depth feasibility assessment.' },

  // Regular Verbs (High Frequency in TOEIC Parts 1, 2, 5 & 6)
  { infinitive: 'accept', pastSimple: 'accepted', pastParticiple: 'accepted', spanish: 'aceptar / recibir', type: 'regular', example: 'The venue accepted our revised catering request.' },
  { infinitive: 'accompany', pastSimple: 'accompanied', pastParticiple: 'accompanied', spanish: 'acompañar', type: 'regular', example: 'A licensed technician accompanied the visitors during the plant tour.' },
  { infinitive: 'achieve', pastSimple: 'achieved', pastParticiple: 'achieved', spanish: 'lograr / alcanzar', type: 'regular', example: 'The engineering division achieved record reliability scores.' },
  { infinitive: 'acquire', pastSimple: 'acquired', pastParticiple: 'acquired', spanish: 'adquirir / comprar', type: 'regular', example: 'The media group acquired two regional digital publications.' },
  { infinitive: 'adjust', pastSimple: 'adjusted', pastParticiple: 'adjusted', spanish: 'ajustar / regular', type: 'regular', example: 'The speaker adjusted the microphone before addressing the audience.' },
  { infinitive: 'advise', pastSimple: 'advised', pastParticiple: 'advised', spanish: 'aconsejar / sugerir', type: 'regular', example: 'The legal advisor advised us to review the indemnity clause.' },
  { infinitive: 'announce', pastSimple: 'announced', pastParticiple: 'announced', spanish: 'anunciar / comunicar', type: 'regular', example: 'The airline announced a minor gate change over the intercom.' },
  { infinitive: 'apply', pastSimple: 'applied', pastParticiple: 'applied', spanish: 'postular / aplicar', type: 'regular', example: 'More than forty candidates applied for the senior position.' },
  { infinitive: 'appoint', pastSimple: 'appointed', pastParticiple: 'appointed', spanish: 'nombrar / designar', type: 'regular', example: 'The board appointed Ms. Tanaka as head of public relations.' },
  { infinitive: 'approve', pastSimple: 'approved', pastParticiple: 'approved', spanish: 'aprobar / autorizar', type: 'regular', example: 'The municipal council approved our construction permit.' },
  { infinitive: 'arrange', pastSimple: 'arranged', pastParticiple: 'arranged', spanish: 'organizar / coordinar', type: 'regular', example: 'Our administrative assistant arranged airport transportation.' },
  { infinitive: 'attend', pastSimple: 'attended', pastParticiple: 'attended', spanish: 'asistir a', type: 'regular', example: 'Over two hundred representatives attended the symposium.' },
  { infinitive: 'cancel', pastSimple: 'canceled', pastParticiple: 'canceled', spanish: 'cancelar / anular', type: 'regular', example: 'The outdoor seminar was canceled due to heavy rain.' },
  { infinitive: 'confirm', pastSimple: 'confirmed', pastParticiple: 'confirmed', spanish: 'confirmar / ratificar', type: 'regular', example: 'The hotel confirmed our reservation details via email.' },
  { infinitive: 'consider', pastSimple: 'considered', pastParticiple: 'considered', spanish: 'considerar / evaluar', type: 'regular', example: 'The committee considered several design proposals.' },
  { infinitive: 'delay', pastSimple: 'delayed', pastParticiple: 'delayed', spanish: 'retrasar / postergar', type: 'regular', example: 'Road construction delayed the morning shuttle service.' },
  { infinitive: 'deliver', pastSimple: 'delivered', pastParticiple: 'delivered', spanish: 'entregar / despachar', type: 'regular', example: 'The courier delivered the signed contracts before noon.' },
  { infinitive: 'demonstrate', pastSimple: 'demonstrated', pastParticiple: 'demonstrated', spanish: 'demostrar / exhibir uso', type: 'regular', example: 'The vendor demonstrated the software’s automated backup features.' },
  { infinitive: 'display', pastSimple: 'displayed', pastParticiple: 'displayed', spanish: 'mostrar / exhibir', type: 'regular', example: 'Ceramic products were attractively displayed in the storefront.' },
  { infinitive: 'examine', pastSimple: 'examined', pastParticiple: 'examined', spanish: 'examinar / revisar', type: 'regular', example: 'Quality inspectors examined every batch before shipment.' },
  { infinitive: 'expand', pastSimple: 'expanded', pastParticiple: 'expanded', spanish: 'expandir / ampliar', type: 'regular', example: 'The retail chain expanded its footprint across Latin America.' },
  { infinitive: 'explain', pastSimple: 'explained', pastParticiple: 'explained', spanish: 'explicar / detallar', type: 'regular', example: 'The instructor clearly explained the safety procedures.' },
  { infinitive: 'improve', pastSimple: 'improved', pastParticiple: 'improved', spanish: 'mejorar / optimizar', type: 'regular', example: 'The redesign significantly improved website navigation.' },
  { infinitive: 'increase', pastSimple: 'increased', pastParticiple: 'increased', spanish: 'aumentar / incrementar', type: 'regular', example: 'Online subscriptions increased by twenty-five percent.' },
  { infinitive: 'inform', pastSimple: 'informed', pastParticiple: 'informed', spanish: 'informar / avisar', type: 'regular', example: 'The captain informed passengers of a slight tailwind.' },
  { infinitive: 'install', pastSimple: 'installed', pastParticiple: 'installed', spanish: 'instalar / colocar', type: 'regular', example: 'The IT technician installed the latest operating system update.' },
  { infinitive: 'introduce', pastSimple: 'introduced', pastParticiple: 'introduced', spanish: 'introducir / presentar', type: 'regular', example: 'The manager introduced our new project coordinator.' },
  { infinitive: 'manage', pastSimple: 'managed', pastParticiple: 'managed', spanish: 'gestionar / administrar', type: 'regular', example: 'He successfully managed the warehouse transition.' },
  { infinitive: 'notify', pastSimple: 'notified', pastParticiple: 'notified', spanish: 'notificar / avisar', type: 'regular', example: 'We will notify you immediately once your package is dispatched.' },
  { infinitive: 'obtain', pastSimple: 'obtained', pastParticiple: 'obtained', spanish: 'obtener / conseguir', type: 'regular', example: 'Applicants must obtain clearance before entering the laboratory.' },
  { infinitive: 'participate', pastSimple: 'participated', pastParticiple: 'participated', spanish: 'participar', type: 'regular', example: 'Many local employees participated in the charity run.' },
  { infinitive: 'postpone', pastSimple: 'postponed', pastParticiple: 'postponed', spanish: 'posponer / aplazar', type: 'regular', example: 'The board postponed the meeting until next Wednesday.' },
  { infinitive: 'prepare', pastSimple: 'prepared', pastParticiple: 'prepared', spanish: 'preparar / elaborar', type: 'regular', example: 'The chef prepared seasonal dishes for the luncheon.' },
  { infinitive: 'provide', pastSimple: 'provided', pastParticiple: 'provided', spanish: 'proveer / suministrar', type: 'regular', example: 'The handbook provides comprehensive guidelines on office safety.' },
  { infinitive: 'receive', pastSimple: 'received', pastParticiple: 'received', spanish: 'recibir / acoger', type: 'regular', example: 'We received your online feedback form this morning.' },
  { infinitive: 'recommend', pastSimple: 'recommended', pastParticiple: 'recommended', spanish: 'recomendar', type: 'regular', example: 'The travel specialist recommended booking train tickets early.' },
  { infinitive: 'reduce', pastSimple: 'reduced', pastParticiple: 'reduced', spanish: 'reducir / abaratar', type: 'regular', example: 'Energy-efficient bulbs reduced our monthly utility bill.' },
  { infinitive: 'remind', pastSimple: 'reminded', pastParticiple: 'reminded', spanish: 'recordar a alguien', type: 'regular', example: 'She reminded all team members about the quarterly review.' },
  { infinitive: 'repair', pastSimple: 'repaired', pastParticiple: 'repaired', spanish: 'reparar / arreglar', type: 'regular', example: 'The maintenance crew repaired the elevator within an hour.' },
  { infinitive: 'replace', pastSimple: 'replaced', pastParticiple: 'replaced', spanish: 'reemplazar / sustituir', type: 'regular', example: 'We replaced the outdated printers with wireless scanners.' },
  { infinitive: 'request', pastSimple: 'requested', pastParticiple: 'requested', spanish: 'solicitar / pedir', type: 'regular', example: 'The client requested an itemized invoice for the service.' },
  { infinitive: 'schedule', pastSimple: 'scheduled', pastParticiple: 'scheduled', spanish: 'programar / agendar', type: 'regular', example: 'The keynote presentation is scheduled for 10:30 AM.' },
  { infinitive: 'submit', pastSimple: 'submitted', pastParticiple: 'submitted', spanish: 'enviar / presentar', type: 'regular', example: 'All candidates submitted their portfolios ahead of time.' },
  { infinitive: 'suggest', pastSimple: 'suggested', pastParticiple: 'suggested', spanish: 'sugerir / proponer', type: 'regular', example: 'The architect suggested using natural lighting in the lobby.' }
];
